vtk_module(vtkCMBIO
  DEPENDS
    vtkCMBGeneral
    vtkIOXML
  PRIVATE_DEPENDS
    vtkCMBMeshing
    vtkFiltersGeometry
    vtkGeovisCore
    vtkInteractionStyle
#    vtkIOExport
    vtkIOGDAL
    vtkIOParallelExodus
    vtkRendering${VTK_RENDERING_BACKEND}
    vtkRenderingFreeType
    vtkPVVTKExtensionsDefault
    vtkSMTKMeshingExt
    vtksys
  EXCLUDE_FROM_WRAP_HIERARCHY
)
