vtk_module(vtkCMBFiltering
  DEPENDS
    vtkCMBIO
    vtkFiltersCore
    vtkFiltersExtraction
    vtkFiltersGeometry
  PRIVATE_DEPENDS
    vtkInteractionStyle
    vtkIOLegacy
    vtkRendering${VTK_RENDERING_BACKEND}
    vtkRenderingFreeType
    vtksys
   EXCLUDE_FROM_WRAP_HIERARCHY
)
