//=========================================================================
//  Copyright (c) Kitware, Inc.
//  All rights reserved.
//  See LICENSE.txt for details.
//
//  This software is distributed WITHOUT ANY WARRANTY; without even
//  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
//  PURPOSE.  See the above copyright notice for more information.
//=========================================================================

#ifndef __pqCMBAppCommonInit_h
#define __pqCMBAppCommonInit_h

#include "cmbAppCommonExport.h"
#include "cmbSystemConfig.h"

/// pqCMBAppCommonInit() is for initializing static data when cmbAppCommon
/// is built as a static library.  Otherwise, linkers may drop out entire
/// object files such as files generated by rcc or other files in cmbAppCommon.

CMBAPPCOMMON_EXPORT void pqCMBAppCommonInit();

#endif
