vtk_module(vtkCMBGeneral
  DEPENDS
    vtkCommonDataModel
    vtkCommonExecutionModel
  PRIVATE_DEPENDS
    vtkChartsCore
    vtkFiltersSources
    vtkInteractionStyle
    vtkRenderingFreeType
    vtkRendering${VTK_RENDERING_BACKEND}
    vtksys
  EXCLUDE_FROM_WRAP_HIERARCHY
)
