vtk_module(vtkCMBGeneral
  DEPENDS
    vtkCommonDataModel
    vtkCommonExecutionModel
  PRIVATE_DEPENDS
    vtkChartsCore
    vtksys
    vtkFiltersSources
    vtkInteractionStyle
    vtkRendering${VTK_RENDERING_BACKEND}
    vtkRenderingFreeType
    vtkRenderingFreeType${VTK_RENDERING_BACKEND}
  EXCLUDE_FROM_WRAP_HIERARCHY
)
