vtk_module(vtkDiscreteModel
  GROUPS
   CmbCore
  DEPENDS
    vtkCommonDataModel
    vtkIOCore
    vtkFiltersCore
    vtkRenderingCore
  PRIVATE_DEPENDS
    vtkFiltersSources
    vtkInteractionStyle
    vtkIOXMLParser
    vtkRenderingFreeType${VTK_RENDERING_BACKEND}
    vtkRendering${VTK_RENDERING_BACKEND}
    vtksys
  EXCLUDE_FROM_WRAP_HIERARCHY
)
