vtk_module(vtkCMBGraphics
  DEPENDS
    vtkCMBGeneral
    vtkPVClientServerCoreRendering
  PRIVATE_DEPENDS
    vtkCMBMeshing
    vtkFiltersFlowPaths
    vtkSMTKMeshingExt
    vtksys
  EXCLUDE_FROM_WRAP_HIERARCHY
)
