/*=========================================================================

 Program:   Visualization Toolkit
 Module:    $RCSfile: pqCMBMeshReaderPanel.h,v $

 =========================================================================*/
// .NAME pqCMBMeshReaderPanel - Custom object panel for vtkCMBMeshReader
// .SECTION Description
// Custom adjustments to the automatically generated object panel for the
// vtkCMBMeshReader
#include "pqAutoGeneratedObjectPanel.h"
#include "cmbSystemConfig.h"

class pqCMBMeshReaderPanel : public pqAutoGeneratedObjectPanel
{
  Q_OBJECT
public:
  pqCMBMeshReaderPanel(pqProxy* pxy, QWidget* p);

protected slots:
  void updateInformationAndDomains();
  void updateMaterialControls(int state);
};
