//=========================================================================
//  Copyright (c) Kitware, Inc.
//  All rights reserved.
//  See LICENSE.txt for details.
//
//  This software is distributed WITHOUT ANY WARRANTY; without even
//  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
//  PURPOSE.  See the above copyright notice for more information.
//=========================================================================
// .NAME pqCMBStreamTracerPanel - Custom object panel for vtkCMBStreamTracer
// .SECTION Description
#include "pqAutoGeneratedObjectPanel.h"
#include "cmbSystemConfig.h"

class QFrame;

class pqCMBStreamTracerPanel : public pqAutoGeneratedObjectPanel
{
  typedef pqAutoGeneratedObjectPanel Superclass;
  Q_OBJECT
public:
  pqCMBStreamTracerPanel(pqProxy* pxy, QWidget* p);

public slots:
  /// accept the changes made to the properties
  /// changes will be propogated down to the server manager
  /// subclasses should only change properties when accept is called to work
  /// properly with undo/redo
  virtual void accept();

protected slots:
  void updateInformationAndDomains();
  void updateTestLocationsUI();
  void onTestLocationChanged();

protected:
  void SendDouble3Vector(const char *func,
    int index, double *data);

private:
  QFrame* TestLocationsFrame;
  int NumberOfTestLocations;
};
